name: Deploy MERN Application to VDS

on:
  push:
    branches:
      - main # Укажите ветку, с которой вы хотите деплоить

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          # Клонировать репозиторий на сервер
            ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            
            cd ${{ secrets.SERVER_PATH }}        

            

            # Установка зависимостей
            scp -i ~/.ssh/github -r ./* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/roman
            cp -fRv /var/www/roman/* /home
            rm -rf /var/www/roman
            cd ${{ secrets.SERVER_PATH }}       
            # Сборка фронтенда
            cd client
            npm install
            npm run build

            cd ${{ secrets.SERVER_PATH }}

            # Запуск бэкенда с помощью PM2
            cd server
            npm install
            pm2 restart all || pm2 start server.js --name "server"

            # Перезапуск nginx
            sudo systemctl restart nginx
          EOF
