name: Deploy MERN app to VDS

on:
  push:
    branches:
      - main # или master, если у вас такая ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key for deployment
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          ssh-keyscan -H 62.109.13.68 >> ~/.ssh/known_hosts

      - name: Install dependencies on VDS
        run: |
          ssh -i ~/.ssh/github nuxtvue@62.109.13.68 << 'EOF'
            cd /home/roman
            git pull origin main
            cd server
            npm install
            cd ../client
            npm install
            cd ..
          EOF

      - name: Build frontend with Vite
        run: |
          ssh -i ~/.ssh/id_rsa nuxtvue@62.109.13.68 << 'EOF'
            cd /home/roman/client
            npm run build
          EOF

      - name: Restart backend and frontend services
        run: |
          ssh -i ~/.ssh/id_rsa nuxtvue@62.109.13.68 << 'EOF'
            cd /home/roman
            pm2 restart client  # если используете pm2 для Node.js
            pm2 restart server # если хотите также использовать pm2 для Vite (если применимо)
          EOF
